In [3]:
import h5py
import numpy as np
from tenpy.tools.hdf5_io import load, load_from_hdf5
#import LangGraphExperiments
#import NQSExperiments

for i in range(1):
    j = 96
    h5_filepath = f"data_outputs/wavefunctions/three_site_kagome_{j:03d}.h5"
    print("File name: ", h5_filepath)
    with h5py.File(h5_filepath, 'r+') as f_h5:
        
        #psi = load_from_hdf5(f_h5, 'psi')
        print("f_h5 keys: ", list(f_h5.keys()))
    
        keys = list(f_h5['model_params'].keys())
        print(f"f_h5['model_params'] (input) Keys: {keys}")
        #for key in keys:
        #    print(f"{key} : {f_h5['model_params'][key][()]}")
        #print()
        keys = list(f_h5['observables'].keys())
        print(f"f_h5['observables'] (output) keys: {keys}")
        #for key in keys:
        #    print(f"{key} : {f_h5['observables'][key][:]}")
        #print()
        obs = f_h5['observables']
        spin_corr = obs['spin_corr'][:]
        print("spin correlation matrix:\n", spin_corr)
        charge_density = obs['charge_density'][:]
        print("charge density:\n", charge_density)
        energy = f_h5['energy'][()]
        print(f"energy: \n{energy}")

    

    

File name:  data_outputs/wavefunctions/three_site_kagome_096.h5
f_h5 keys:  ['average_energy', 'average_observables', 'energy', 'model_params', 'observables', 'psi']
f_h5['model_params'] (input) Keys: ['Lx', 'Ly', 'N_elec', 'U', 'bc_x', 'bc_y', 'cons_N', 'cons_Sz', 'explicit_plus_hc', 'mu', 'sort_mpo_legs', 't1', 't2', 'theta_x', 'theta_y']
f_h5['observables'] (output) keys: ['S_q_charge', 'S_q_spin', 'charge_corr', 'charge_density', 'double_occupancy', 'q_vectors', 'spin_corr']
spin correlation matrix:
 [[ 2.04008741e-01 -8.32667268e-17  8.32667268e-17]
 [-8.32667268e-17  1.68873135e-01 -1.45877505e-01]
 [ 8.32667268e-17 -1.45877505e-01  1.68873135e-01]]
charge density:
 [1.17744008 0.91127996 0.91127996]
energy: 
-1.8938014403903225
